### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus-DDL#2]
Download “EdgeLens” data from this link and transfer files in the “Worker”
folder to the, just created, EdgeLens folder. in the /var/www/html/ path.
On terminal run the following commands to run the Analyzer:
1 cd /var/www/html/EdgeLens
2 sudo chmod 777 ∗
3 javac ./analyzer.java
4 java analyzer

Issues
1. Given link is not working, rather showing it as 404 Error. How to download?
2. Transfer files in the “Worker” folder to the, just created, EdgeLens folder.  No worker folder here.
3. javac ./analyzer.java. Unable to compile as file file doesnot exist.

please solve these.

Thanks,

**Comment by shreshthtuli** [comment]
You can transfer the contents of the EdgeLens folder of this repo to /var/www/html/EdgeLens/. Analyzer is not requried here.
