### ISSUE TITLE
Issue at Running EdgeLens

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus-DDL#3]
pi@raspberrypi:~ $ cd /var/www/html/EdgeLens/
pi@raspberrypi:/var/www/html/EdgeLens $ ./run.sh
Traceback (most recent call last):
  File "test_images.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Please Solve This.

Thanks,

**Comment by shreshthtuli** [comment]
First install required packages using: python3 -m pip install -r Yolo/requirements.txt
